const $=id=>document.getElementById(id);const $$=s=>Array.from(document.querySelectorAll(s));
const mk=(t,s)=>'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="900"><rect width="600" height="900" fill="#edf4fb"/><circle cx="210" cy="380" r="100" fill="#315f9d" opacity=".16"/><rect x="300" y="280" width="150" height="360" rx="75" fill="#b98a47" opacity=".22"/><text x="300" y="720" text-anchor="middle" font-family="Arial" font-size="42" font-weight="700" fill="#233e66">${t}</text><text x="300" y="770" text-anchor="middle" font-family="Arial" font-size="26" fill="#64748b">${s}</text></svg>`);
let imgs=[['圖一 / Image 1','人物照片 / Person Photo',mk('人物參考','Person')],['圖二 / Image 2','動物照片 / Animal Photo',mk('動物參考','Animal')],['圖三 / Image 3','場景照片 / Scene Photo',mk('場景參考','Scene')],['圖四 / Image 4','參考風格 1 / Style Reference 1',mk('風格參考','Style 1')],['圖五 / Image 5','參考風格 2 / Style Reference 2',mk('風格參考','Style 2')]];
function styles(){return $$('#styleChips input:checked').map(x=>x.value).join('、')||'Vogue 風格奢華時尚廣告'}
function animal(){let a=$('animalType').value;return a==='自定義'&&$('customAnimal').value.trim()?$('customAnimal').value.trim():a}
function scene(){return $('customLocation').value.trim()||$('landmark').value}
function promptText(){let a=animal(),sc=scene(),st=styles(),ar=$('aspectRatio').value;let az=a==='AI 隨機選擇'?'由 AI 從獅子、豹、黑貓、獵豹、美洲獅、美洲豹、北極熊、台灣黑熊、黑狼、雪狼、巴哥犬、緬因貓、比熊犬等真實地球動物中隨機選擇一種。':`指定動物為「${a}」。`;let zh=`以使用者上傳人物作為主模特兒參考，保留主要外觀、髮型輪廓與整體氣質。於人物「${$('position').selectedOptions[0].textContent}」安排一隻「${$('animalScale').value}」的巨大真實地球動物，作為強大的伸展台夥伴。${az}動物必須是生物學上真實可信的地球動物，不可為神話生物、奇幻野獸、魔法獸或超自然生物。\n\n人物與巨型動物「${$('interaction').value}」，採「${$('composition').value}」，形成強烈比例對比、時尚張力與精品廣告感。場景設定為「${sc}」，光線為「${$('lighting').value}」。動物佩戴與人物「${$('personStyle').value}」造型相符的「${$('animalStyle').value}」。整體風格為 ${st}。人物與動物之間需有清楚明暗與色彩區分，背景可柔和退後，但人物與動物都需清楚銳利。輸出比例：${ar}。`;let en=`Use the uploaded person as the main model reference. Place one giant real earth animal near the main person as a powerful runway companion. Animal setting: ${a}. The animal scale should be ${$('animalScale').value}, oversized yet biologically believable, never mythical, fantasy-based, magical, or supernatural.\n\nShow the person and the animal ${$('interaction').value} in a ${$('composition').value}. Use ${sc} as the scene with ${$('lighting').value}. The animal should wear ${$('animalStyle').value} matching the person’s ${$('personStyle').value} styling. Overall style: ${st}. Keep person and animal clearly separated by light, color, and contrast. Aspect ratio: ${ar}.`;return {zh,en}}
function draw(){let rows=imgs.map((r,i)=>`<div class="upload-row"><img src="${r[2]}"><div><strong>${r[0]}</strong><small>${r[1]}</small></div><div class="row-actions"><button class="icon-btn delete" data-del="${i}">⌫</button><button class="icon-btn" data-up="${i}">↑</button><button class="icon-btn" data-down="${i}">↓</button></div></div>`).join('');$('uploadOrder').innerHTML=rows;$('thumbPreview').innerHTML=imgs.map(r=>`<div class="thumb"><img src="${r[2]}"><strong>${r[0]}</strong><small>${r[1]}</small></div>`).join('')}
function update(){let p=promptText();$('zhPrompt').value=p.zh;$('enPrompt').value=p.en;$('constraints').value='只能出現一隻真實地球動物\n不固定為老虎\n不要神話生物、奇幻野獸、魔法獸或超自然生物\n不要黑對黑融合\n不要額外人物\n不要畸形解剖、扭曲肢體、錯誤比例\n不要漂浮配件\n不要文字、浮水印、品牌亂碼\n不要卡通風格、插畫風格、低解析\n不要模糊人物主要特徵';$('negativePrompt').value='only one real earth animal, no tiger-only default, no mythical creature, no fantasy beast, no extra people, no text, no watermark, no cartoon style, no low resolution, no blurry main subject';$('inferredVariables').innerHTML=[`動物配件：${$('animalStyle').value}`,`光線：${$('lighting').value}`,`鏡頭：${$('composition').value}`,`場景：${scene()}`,`輸出比例：${$('aspectRatio').value}`].map(x=>`<span>${x}</span>`).join('');draw()}
function copy(id){navigator.clipboard.writeText($(id).value||'').then(()=>alert('已複製 / Copied'))}
function exportJson(){let payload={parameters:{personStyle:$('personStyle').value,animal:animal(),scene:scene(),aspectRatio:$('aspectRatio').value,styles:styles()},prompts:{zh:$('zhPrompt').value,en:$('enPrompt').value,constraints:$('constraints').value,negative:$('negativePrompt').value}};let b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='fashion-animal-prompt-studio.json';a.click()}
function readFile(input){let f=input.files&&input.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{imgs.unshift(['上傳圖片 / Uploaded','User Photo',rd.result]);let box=document.querySelector(`[data-slot="${input.dataset.upload}"]`);if(box)box.innerHTML=`<img src="${rd.result}">`;update()};rd.readAsDataURL(f)}
document.addEventListener('input',update);document.addEventListener('change',e=>{if(e.target.matches('[data-upload]'))readFile(e.target);else update()});document.addEventListener('click',e=>{let t=e.target;if(t.id==='copyAllBtn')navigator.clipboard.writeText($('zhPrompt').value+'\n\n---\n\n'+$('enPrompt').value+'\n\n---\n\n'+$('negativePrompt').value).then(()=>alert('已複製全部 / Copied all'));if(t.id==='exportJsonBtn')exportJson();if(t.id==='resetBtn')location.reload();if(t.dataset.copy)copy(t.dataset.copy);if(t.dataset.del){imgs.splice(+t.dataset.del,1);update()}if(t.dataset.up){let i=+t.dataset.up;if(i>0){[imgs[i-1],imgs[i]]=[imgs[i],imgs[i-1]];update()}}if(t.dataset.down){let i=+t.dataset.down;if(i<imgs.length-1){[imgs[i+1],imgs[i]]=[imgs[i],imgs[i+1]];update()}}});update();